spring:
  config:
    activate:
      on-profile: cache
    import: optional:file:/external/mortgage-rates.yml

  cache:
    type: redis

  redis:
    host: ${SPRING_DATA_REDIS_HOST:redis}
    port: ${SPRING_DATA_REDIS_PORT:6379}
    time-to-live: 600s

  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:db}:5432/mydb
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: caches,health,info,env

mortgage:
  rates:
    - maturity: 5
      interest: 2.0
      lastUpdate: 2026-01-31T10:15:30
    - maturity: 10
      interest: 3.0
      lastUpdate: 2026-01-31T10:15:30
    - maturity: 15
      interest: 3.5
      lastUpdate: 2026-01-31T10:15:30
    - maturity: 20
      interest: 4.0
      lastUpdate: 2026-01-31T10:15:30