spring:
  application:
    name: mortgage
  cache:
    type: none
  profiles:
    default: in-memory

management:
  endpoints:
    web:
      exposure:
        include: health,info,env

server:
  port: 8080
